# Stub file for Pylance/mypy: exposes all numpy symbols so that
# `import cunumpy as xp` followed by `xp.<Tab>` shows numpy completions.
# At runtime the real __init__.py dispatches to numpy or cupy via __getattr__.
from collections.abc import Generator
from contextlib import contextmanager
from typing import Any

import numpy as np
from numpy import *

from . import algorithms as algorithms
from . import cuda as cuda
from . import kernels as kernels
from . import memory as memory
from . import mpi as mpi
from . import petsc as petsc
from . import profiling as profiling
from . import rng as rng
from . import xp as xp
from ._scipy_backend import scipy as scipy

def to_numpy(array: Any) -> np.ndarray: ...
def to_cupy(array: Any) -> Any: ...
def to_cunumpy(array: Any) -> Any: ...
def cupy_available() -> bool: ...
def backend_info() -> dict[str, Any]: ...
def get_array_module(array: Any) -> Any: ...
def get_backend() -> str: ...
def get_array_backend(array: Any) -> str: ...
def is_gpu(array: Any) -> bool: ...
def is_cpu(array: Any) -> bool: ...
def same_backend(*arrays: Any) -> bool: ...
def assert_same_backend(*arrays: Any) -> None: ...
@contextmanager
def use_backend(backend: str, *, strict: bool = ...) -> Generator[None]: ...
def set_backend(backend: str, *, strict: bool = ...) -> None: ...
def require_version(minimum: str) -> None: ...
def default_float_dtype() -> Any: ...
def synchronize() -> None: ...
def as_device_array(
    value: Any, dtype: Any = ..., ndim: int | None = ..., *, name: str | None = ...
) -> Any: ...

numpy_backend: bool
cupy_backend: bool
__version__: str
