"""Interface for calling Pyccel-compiled kernels with CuPy arrays.

Kernels generated by `pyccel <https://github.com/pyccel/pyccel>`_ are compiled
C/Fortran routines that only understand NumPy (host) arrays. :class:`PyccelKernel`
wraps such a kernel so that it can be called transparently with CuPy (device)
arrays: the arguments are copied to the host before the call, in-place updates
made by the kernel are copied back to the device afterwards, and any arrays
returned by the kernel are moved back to the device.

On the NumPy backend the wrapper is a no-op and the kernel is called directly.
Ordinary Python callables are supported, including in Pyodide. This module
neither imports Pyccel nor compiles kernels; compilation, if desired, is the
caller's responsibility.

Argument objects that have a host and a device form implement the
:class:`KernelArguments` protocol: ``__host_args__()`` returns what the host
kernel receives in that position, ``__cuda_args__()`` what a
:class:`~cunumpy.cuda.CudaKernel` receives. :class:`PyccelKernel` and
:class:`~cunumpy.kernels.Kernel` resolve ``__host_args__()`` with
:func:`resolve_host_args` before calling the host kernel.
"""

from __future__ import annotations

import copy
import importlib
import os
import warnings
from collections.abc import Callable, Generator, Iterator, Mapping, Sequence
from contextlib import contextmanager
from types import ModuleType
from typing import Any

import array_api_compat
import numpy as np

from cunumpy._transfers import _ACTIVE as _COUNTERS
from cunumpy._transfers import _describe, _is_device_copy, _nbytes, _record
from cunumpy.xp import _cupy_backend, _to_cupy, _to_numpy, is_gpu, to_cupy, to_numpy

__all__ = ["CompiledHostKernel", "KernelArguments", "PyccelKernel", "resolve_host_args"]


class KernelArguments:
    """Base class for argument objects with a host form and a device form.

    A kernel argument that stands for a group of arrays, e.g. all marker data
    of a particle species, usually exists twice: as an object holding NumPy
    arrays for the host kernel (e.g. a Pyccel class) and as device arrays for
    the CUDA kernel. This protocol lets one object represent both, so that a
    call to a :class:`~cunumpy.kernels.Kernel` never branches on the backend:

    * ``__host_args__()`` returns the single object that the host kernel
      receives in that position; :class:`PyccelKernel` and
      :class:`~cunumpy.kernels.Kernel` resolve it (top-level positional and keyword
      arguments only) before calling the host kernel;
    * ``__cuda_args__()`` returns the tuple of CUDA kernel arguments the object
      stands for (the :class:`~cunumpy.cuda.CudaArguments` protocol);
      :class:`~cunumpy.cuda.CudaKernel` flattens it into the kernel parameters.

    Subclassing is optional: any object whose *type* defines a callable
    ``__host_args__`` is resolved (an instance attribute of that name is not).
    Both methods of this base class raise ``NotImplementedError``; a subclass
    overrides the ones it supports.

    Examples
    --------
    Build each form lazily on first access, so that a CPU run never builds
    device arguments and a GPU run never builds the host object:

    >>> class Particles:
    ...     def __init__(self, markers):
    ...         self.markers = markers  # NumPy or CuPy array
    ...         self._kernel_args = None
    ...
    ...     @property
    ...     def kernel_args(self):
    ...         if self._kernel_args is None:
    ...             self._kernel_args = ParticleArguments(self)
    ...         return self._kernel_args
    ...
    >>> class ParticleArguments(xp.kernels.KernelArguments):
    ...     def __init__(self, particles):
    ...         self._particles = particles
    ...         self._host = None
    ...         self._cuda = None
    ...
    ...     def __host_args__(self):
    ...         if self._host is None:  # e.g. a Pyccel class of NumPy arrays
    ...             self._host = MarkerArguments(self._particles.markers)
    ...         return self._host
    ...
    ...     def __cuda_args__(self):
    ...         if self._cuda is None:  # device arrays and scalars, flattened
    ...             markers = self._particles.markers
    ...             self._cuda = (markers, markers.shape[0], markers.shape[1])
    ...         return self._cuda
    ...
    >>> push(particles.kernel_args, dt, n_threads=n)  # doctest: +SKIP

    ``push`` receives ``MarkerArguments(...)`` on the NumPy backend and
    ``(markers, n_rows, n_cols)`` on the CuPy backend. Invalidate the cached
    forms (set them to ``None``) whenever the arrays are replaced, e.g. after
    resizing, ``deepcopy`` or unpickling.
    """

    def __host_args__(self) -> Any:
        """The object passed to the host kernel in place of this one."""
        raise NotImplementedError(
            f"{type(self).__name__} does not provide host kernel arguments "
            "(implement __host_args__)",
        )

    def __cuda_args__(self) -> tuple[Any, ...]:
        """The CUDA kernel arguments this object stands for."""
        raise NotImplementedError(
            f"{type(self).__name__} does not provide CUDA kernel arguments "
            "(implement __cuda_args__)",
        )


def _host_args(value: Any) -> Any:
    """`value.__host_args__()` if its type defines the method, else `value`."""
    # checked on the class, so that an instance attribute of that name (e.g. a
    # stored object or None) is not mistaken for the protocol
    if callable(getattr(type(value), "__host_args__", None)):
        return value.__host_args__()
    return value


def resolve_host_args(
    args: Sequence[Any],
    kwargs: Mapping[str, Any] | None = None,
) -> tuple[tuple[Any, ...], dict[str, Any]]:
    """Replace :class:`KernelArguments` objects by their host form.

    Every top-level positional and keyword argument whose type defines a
    callable ``__host_args__()`` is replaced by the value it returns; all other
    arguments (including objects nested in tuples, lists or dicts) are passed
    through untouched.

    Parameters
    ----------
    args : Sequence
        Positional arguments.
    kwargs : Mapping[str, Any] | None
        Keyword arguments.

    Returns
    -------
    tuple[tuple, dict]
        The resolved positional and keyword arguments.
    """
    return (
        tuple(_host_args(arg) for arg in args),
        {name: _host_args(value) for name, value in (kwargs or {}).items()},
    )


# The conversions between device and host arrays, as module attributes so that
# tests can substitute a fake device array type without a GPU. They bypass the
# per-array transfer counting: a call that converts is counted once, as a
# ``kernel_conversion`` event, in :meth:`PyccelKernel.__call__`.
_is_device_array = array_api_compat.is_cupy_array
_device_to_host = _to_numpy
_host_to_device = _to_cupy


class PyccelKernel:
    """Call a NumPy callable or Pyccel-compiled kernel with NumPy or CuPy arrays.

    Parameters
    ----------
    kernel : callable
        The pyccelized kernel (or any callable expecting NumPy arrays).
    use_cupy : bool, optional
        Force host/device conversion on (``True``) or off (``False``). By
        default (``None``) it is decided at call time: conversion happens when
        the active backend is CuPy or when a CuPy array is passed in.
    object_modules : sequence of str, optional
        Module prefixes (e.g. ``("struphy.", "feectools.")``) whose instances
        should be traversed attribute-by-attribute when looking for arrays to
        convert. Objects from other modules are passed through untouched.
    is_array : callable, optional
        Predicate deciding whether a host-side value returned by the kernel
        (or reachable from a declared output) counts as an array to move
        back to the device. Defaults to ``isinstance(value, np.ndarray)``.
        Override this if the kernel returns/mutates a NumPy subclass or a
        custom host array type that should also be converted back to CuPy.
    outputs : sequence of int or str, optional
        Which arguments the kernel writes to. Only those are copied back to the
        device after the call, which avoids pointless device transfers for the
        (usually much larger) read-only inputs. Positional arguments are named
        by index, keyword arguments by name::

            interpolate = PyccelKernel(some_interpolation_kernel, outputs=(5,))
            interpolate(x, y, z, basis, coeffs, out)  # `out` is argument 5

        Pyccel-compiled kernels are builtins with no introspectable signature,
        so an index and a name are *not* interchangeable: declare the form you
        actually call with. An empty sequence declares that the kernel writes to
        none of its arguments. By default (``None``) every converted array is
        copied back, which is always correct but does more work.

    Notes
    -----
    Top-level arguments implementing :class:`KernelArguments` (a
    ``__host_args__()`` method on their type) are replaced by their host form
    before anything else, so the same argument objects can be passed to a
    ``PyccelKernel`` and to a :class:`~cunumpy.cuda.CudaKernel`.

    Examples
    --------
    >>> from cunumpy.kernels import PyccelKernel
    >>> kernel = PyccelKernel(my_pyccelized_function)
    >>> kernel(out, x, y)  # `out`, `x`, `y` may be NumPy or CuPy arrays
    """

    def __init__(
        self,
        kernel: Callable[..., Any],
        use_cupy: bool | None = None,
        object_modules: Sequence[str] = (),
        is_array: Callable[[Any], bool] | None = None,
        outputs: Sequence[int | str] | None = None,
    ) -> None:
        self._kernel = kernel
        self._use_cupy = use_cupy
        self._object_modules = tuple(object_modules)
        self._is_array = is_array or (lambda value: isinstance(value, np.ndarray))

        if outputs is None:
            self._outputs: tuple[int | str, ...] | None = None
        else:
            if isinstance(outputs, (int, str)):
                raise TypeError(
                    "outputs must be a sequence of argument indices/names, "
                    f"not a bare {type(outputs).__name__} "
                    f"(did you mean outputs=({outputs!r},)?)",
                )
            for entry in outputs:
                if not isinstance(entry, (int, str)) or isinstance(entry, bool):
                    raise TypeError(
                        "outputs entries must be argument indices (int) or "
                        f"names (str), got {entry!r}",
                    )
            self._outputs = tuple(outputs)

    def __repr__(self) -> str:
        return (
            f"PyccelKernel(kernel={self.name!r}, use_cupy={self.use_cupy!r}, "
            f"outputs={self._outputs!r})"
        )

    def _convert_to_numpy(
        self,
        value: Any,
        converted: list[tuple[Any, np.ndarray]],
        memo: dict[int, Any],
    ) -> Any:
        """Recursively replace CuPy arrays in `value` by host copies.

        Every replacement is appended to `converted` as a
        ``(device_array, host_copy)`` pair.

        `memo` maps ``id(original) -> converted`` and is shared across all
        arguments of a single call. It serves two purposes: a device array
        reachable by several paths is copied to the host exactly once (so the
        kernel sees one shared array, as the caller intended, and the write-back
        happens once), and reference cycles terminate instead of recursing
        forever. Everything traversed here stays reachable from the caller's
        arguments for the duration of the call, so the `id` keys cannot be
        reused by unrelated objects.
        """
        key = id(value)
        if key in memo:
            return memo[key]

        if _is_device_array(value):
            value_np = _device_to_host(value)
            if _COUNTERS:
                _record(
                    "to_host",
                    f"PyccelKernel {self.name!r} input ({_describe(value)})",
                    nbytes=_nbytes(value_np),
                )
            memo[key] = value_np
            converted.append((value, value_np))
            return value_np

        if isinstance(value, tuple):
            # A tuple cannot be memoized before its items are converted, but it
            # can only take part in a cycle through a mutable container, and
            # those are memoized before they are filled in below.
            value_np = tuple(
                self._convert_to_numpy(item, converted, memo) for item in value
            )
            memo[key] = value_np
            return value_np

        if isinstance(value, list):
            value_np = []
            memo[key] = value_np
            value_np.extend(
                self._convert_to_numpy(item, converted, memo) for item in value
            )
            return value_np

        if isinstance(value, dict):
            value_np = {}
            memo[key] = value_np
            for k, v in value.items():
                value_np[k] = self._convert_to_numpy(v, converted, memo)
            return value_np

        if hasattr(value, "__dict__") and value.__class__.__module__.startswith(
            self._object_modules,
        ):
            # Shallow-copy the object so the caller's instance keeps pointing at
            # its device arrays; only the copy holds the host views.
            value_np = copy.copy(value)
            memo[key] = value_np
            for name, attr in vars(value).items():
                setattr(value_np, name, self._convert_to_numpy(attr, converted, memo))
            return value_np

        return value

    def _convert_from_numpy(self, value: Any) -> Any:
        """Move host arrays returned by the kernel back to the device."""
        if self._is_array(value):
            return self._copy_to_device(value)
        if isinstance(value, tuple):
            return tuple(self._convert_from_numpy(item) for item in value)
        if isinstance(value, list):
            return [self._convert_from_numpy(item) for item in value]
        return value

    def _copy_to_device(self, value: Any) -> Any:
        result = _host_to_device(value)
        if _COUNTERS:
            _record(
                "to_device",
                f"PyccelKernel {self.name!r} output ({_describe(value)})",
                nbytes=_nbytes(value),
            )
        return result

    def _collect_host_arrays(self, value: Any, found: set[int], seen: set[int]) -> None:
        """Record the id of every host array reachable from `value`.

        Runs over the *converted* arguments, using the same traversal rules as
        :meth:`_convert_to_numpy`, so that an output declared as a container or
        an object contributes the arrays nested inside it.
        """
        if self._is_array(value):
            found.add(id(value))
            return

        if id(value) in seen:
            return

        if isinstance(value, (tuple, list)):
            seen.add(id(value))
            for item in value:
                self._collect_host_arrays(item, found, seen)
            return

        if isinstance(value, dict):
            seen.add(id(value))
            for item in value.values():
                self._collect_host_arrays(item, found, seen)
            return

        if hasattr(value, "__dict__") and value.__class__.__module__.startswith(
            self._object_modules,
        ):
            seen.add(id(value))
            for attr in vars(value).values():
                self._collect_host_arrays(attr, found, seen)

    def _output_host_arrays(
        self,
        args_np: list[Any],
        kwargs_np: dict[str, Any],
    ) -> set[int]:
        """Ids of the host arrays reachable from the declared output arguments.

        Raises
        ------
        IndexError, KeyError
            If a declared output does not correspond to an argument of this
            call -- typically because an argument declared by index was passed
            as a keyword, or vice versa.
        """
        found: set[int] = set()
        seen: set[int] = set()

        for entry in self._outputs or ():
            if isinstance(entry, int):
                index = entry + len(args_np) if entry < 0 else entry
                if not 0 <= index < len(args_np):
                    raise IndexError(
                        f"{self.name}() was declared with output argument "
                        f"{entry}, but was called with {len(args_np)} "
                        "positional argument(s). Note that an output passed as "
                        "a keyword must be declared by name, not by index.",
                    )
                self._collect_host_arrays(args_np[index], found, seen)
            else:
                if entry not in kwargs_np:
                    raise KeyError(
                        f"{self.name}() was declared with output argument "
                        f"{entry!r}, but no such keyword argument was passed. "
                        "Note that an output passed positionally must be "
                        "declared by index, not by name.",
                    )
                self._collect_host_arrays(kwargs_np[entry], found, seen)

        return found

    def _contains_cupy(self, value: Any, seen: set[int] | None = None) -> bool:
        """Whether `value` holds a CuPy array, following the same traversal
        rules as :meth:`_convert_to_numpy`.

        `seen` tracks already-visited containers so that reference cycles
        terminate.
        """
        if _is_device_array(value):
            return True

        if seen is None:
            seen = set()
        if id(value) in seen:
            return False

        if isinstance(value, (tuple, list)):
            seen.add(id(value))
            return any(self._contains_cupy(item, seen) for item in value)

        if isinstance(value, dict):
            seen.add(id(value))
            return any(self._contains_cupy(item, seen) for item in value.values())

        if hasattr(value, "__dict__") and value.__class__.__module__.startswith(
            self._object_modules,
        ):
            seen.add(id(value))
            return any(self._contains_cupy(attr, seen) for attr in vars(value).values())

        return False

    def _needs_conversion(self, args: tuple[Any, ...], kwargs: dict[str, Any]) -> bool:
        if self._use_cupy is not None:
            return self._use_cupy
        if _cupy_backend():
            return True
        # The backend is NumPy, but individual CuPy arrays may still have been
        # passed in explicitly.
        return any(self._contains_cupy(value) for value in (*args, *kwargs.values()))

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        args, kwargs = resolve_host_args(args, kwargs)
        if not self._needs_conversion(args, kwargs):
            return self._kernel(*args, **kwargs)

        # Convert CuPy arrays in args/kwargs to NumPy arrays on the host. The
        # memo is shared across args and kwargs so that an array passed more
        # than once stays a single array on the host too.
        converted: list[tuple[Any, np.ndarray]] = []
        memo: dict[int, Any] = {}
        args_np = [self._convert_to_numpy(x, converted, memo) for x in args]
        kwargs_np = {
            k: self._convert_to_numpy(v, converted, memo) for k, v in kwargs.items()
        }

        # Which arrays the kernel may have written to is resolved before the
        # call, so a mis-declared output is reported even if the kernel itself
        # would have raised first.
        writeable = (
            None
            if self._outputs is None
            else self._output_host_arrays(args_np, kwargs_np)
        )

        if _COUNTERS and converted:
            _record(
                "kernel_conversion",
                f"PyccelKernel {self.name!r}: {len(converted)} device array(s) "
                "copied to the host",
            )

        result = self._kernel(*args_np, **kwargs_np)

        # Copy in-place kernel updates back to the device arrays.
        for device_array, host_array in converted:
            if writeable is None or id(host_array) in writeable:
                device_array[...] = self._copy_to_device(host_array)

        return self._convert_from_numpy(result)

    @property
    def name(self) -> str:
        """Name of the wrapped kernel."""
        return getattr(self._kernel, "__name__", type(self._kernel).__name__)

    @property
    def kernel(self) -> Callable[..., Any]:
        """The wrapped kernel."""
        return self._kernel

    @property
    def use_cupy(self) -> bool:
        """Whether calls currently convert between device and host arrays."""
        if self._use_cupy is not None:
            return self._use_cupy
        return _cupy_backend()

    @property
    def object_modules(self) -> tuple[str, ...]:
        """Module prefixes whose instances are traversed for arrays."""
        return self._object_modules

    @property
    def is_array(self) -> Callable[[Any], bool]:
        """Predicate identifying host values to convert back to the device."""
        return self._is_array

    @property
    def outputs(self) -> tuple[int | str, ...] | None:
        """Declared output arguments, or ``None`` if every array is copied back."""
        return self._outputs


#: The host implementations a kernel folder can have, see `HostImplementations`.
HOST_IMPLEMENTATIONS = ("pyccel", "numba", "numpy", "python")


def _check_implementation(name: str | None) -> str | None:
    if name is not None and name not in HOST_IMPLEMENTATIONS:
        raise ValueError(
            f"kernel implementation must be one of {HOST_IMPLEMENTATIONS} or None, "
            f"got {name!r}",
        )
    return name


_KERNEL_IMPLEMENTATION: str | None = _check_implementation(
    os.environ.get("CUNUMPY_HOST_KERNEL_IMPLEMENTATION", "").strip().lower() or None,
)


def set_kernel_implementation(name: str | None) -> None:
    """Choose the host implementation every kernel runs, like :func:`set_backend`.

    ``"pyccel"``, ``"numba"``, ``"numpy"`` or ``"python"`` (the uncompiled
    source of the pyccel version); None restores the default (see
    :class:`HostImplementations`). A kernel without the chosen implementation,
    or whose chosen implementation is unavailable (e.g. pyccel failed to
    compile), raises instead of running another one. CUDA kernels are not
    affected: device arrays always run the CUDA version. The environment
    variable ``CUNUMPY_HOST_KERNEL_IMPLEMENTATION`` (read when cunumpy is imported)
    sets it for a whole run.
    """
    global _KERNEL_IMPLEMENTATION
    _KERNEL_IMPLEMENTATION = _check_implementation(name)


def get_kernel_implementation() -> str | None:
    """The host implementation set with :func:`set_kernel_implementation`, or None."""
    return _KERNEL_IMPLEMENTATION


@contextmanager
def use_kernel_implementation(name: str | None) -> Iterator[None]:
    """Temporarily choose the host implementation, like :func:`use_backend`.

    For tests and benchmarks, e.g. ``with xp.kernels.use_kernel_implementation("numpy"):``
    to run the code path of a machine without pyccel. The setting is global,
    not per thread.
    """
    global _KERNEL_IMPLEMENTATION
    previous = _KERNEL_IMPLEMENTATION
    set_kernel_implementation(name)
    try:
        yield
    finally:
        _KERNEL_IMPLEMENTATION = previous


class HostImplementations:
    """The host implementations of one kernel, run by name or by the default rule.

    Each implementation is loaded on first use (a pyccel build, an import) and
    may be unavailable (no compiler, numba not installed); a failed load is
    remembered with its exception. A call runs the implementation chosen with
    :func:`set_kernel_implementation`, which must exist and load, or else the
    default: the first available of ``"pyccel"``, ``"numba"`` and ``"numpy"``,
    and as a last resort ``"python"``, with a warning (correct, but slow).
    Built by :meth:`Kernel.from_folder` from the files of a kernel folder.

    Parameters
    ----------
    name : str
        Name of the kernel.
    loaders : Mapping[str, Callable[[], Callable]]
        Per implementation name (one of ``HOST_IMPLEMENTATIONS``), a function
        returning the implementation, or raising if it is unavailable.
    """

    def __init__(
        self,
        name: str,
        loaders: Mapping[str, Callable[[], Callable[..., Any]]],
    ) -> None:
        unknown = set(loaders) - set(HOST_IMPLEMENTATIONS)
        if unknown:
            raise ValueError(
                f"kernel {name!r}: unknown implementations {sorted(unknown)}, "
                f"expected names from {HOST_IMPLEMENTATIONS}",
            )
        if "python" not in loaders:
            raise ValueError(f"kernel {name!r}: the 'python' implementation is needed")
        self.__name__ = name
        self._loaders = dict(loaders)
        self._loaded: dict[str, Callable[..., Any]] = {}
        self.errors: dict[str, BaseException] = {}
        self._default: str | None = None

    def __repr__(self) -> str:
        return f"HostImplementations({self.__name__!r}, {list(self.names)})"

    @property
    def names(self) -> tuple[str, ...]:
        """The implementations this kernel has, loaded or not."""
        return tuple(name for name in HOST_IMPLEMENTATIONS if name in self._loaders)

    @property
    def python(self) -> Callable[..., Any]:
        """The uncompiled Python function (for signatures and reference results)."""
        return self.get("python")

    def available(self, name: str) -> bool:
        """Whether implementation `name` exists and loads (loads it now)."""
        if name not in self._loaders:
            return False
        try:
            self.get(name)
        except Exception:  # noqa: BLE001 -- recorded in errors
            return False
        return True

    def get(self, name: str) -> Callable[..., Any]:
        """Implementation `name`, loaded on first use.

        Raises
        ------
        LookupError
            If the kernel has no such implementation, or it failed to load
            (the load error is the cause).
        """
        function = self._loaded.get(name)
        if function is not None:
            return function
        if name not in self._loaders:
            raise LookupError(
                f"kernel {self.__name__!r} has no {name!r} implementation "
                f"(it has {', '.join(self.names)})",
            )
        if name in self.errors:
            raise LookupError(
                f"the {name!r} implementation of kernel {self.__name__!r} is "
                f"unavailable: {self.errors[name]!r}",
            ) from self.errors[name]
        try:
            function = self._loaders[name]()
        except Exception as error:
            self.errors[name] = error
            raise LookupError(
                f"the {name!r} implementation of kernel {self.__name__!r} is "
                f"unavailable: {error!r}",
            ) from error
        self._loaded[name] = function
        return function

    def selected(self) -> str:
        """The implementation a call runs now (loads the default on first use)."""
        if _KERNEL_IMPLEMENTATION is not None:
            return _KERNEL_IMPLEMENTATION
        if self._default is None:
            for name in ("pyccel", "numba", "numpy"):
                if self.available(name):
                    self._default = name
                    break
            else:
                warnings.warn(
                    f"Kernel {self.__name__!r}: no compiled or NumPy implementation "
                    f"is available ({self.errors!r}); running the uncompiled "
                    "Python version.",
                    RuntimeWarning,
                    stacklevel=3,
                )
                self._default = "python"
        return self._default

    def build(self) -> str:
        """Load the default implementation now, e.g. compile at setup; its name."""
        return self.selected()

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        return self.get(self.selected())(*args, **kwargs)


class CompiledHostKernel:
    """A host kernel compiled on its first call, with a fallback.

    cunumpy does not compile anything itself: `compiler` is the caller's
    function that turns the kernel module into a compiled one, e.g. a wrapper
    around ``pyccel.epyccel`` with a cache, or a function importing modules
    compiled ahead of time.

    Parameters
    ----------
    module : str | ModuleType
        The module that defines the kernel, or its name.
    name : str
        Name of the kernel function in `module`.
    compiler : Callable[[ModuleType], ModuleType]
        Returns the compiled form of the module (with the same function names).
    fallback : Callable | None
        Called instead when compilation fails (e.g. a vectorized NumPy
        implementation with the same arguments). Without one, the uncompiled
        Python function is called, with a warning: correct, but slow.

    Notes
    -----
    :attr:`compiled` builds the kernel and reports whether that worked, so
    that callers can choose another code path; :attr:`error` keeps the
    exception of a failed build.
    """

    def __init__(
        self,
        module: str | ModuleType,
        name: str,
        compiler: Callable[[ModuleType], ModuleType],
        fallback: Callable[..., Any] | None = None,
    ) -> None:
        self._module = module
        self.__name__ = name
        self._compiler = compiler
        self._fallback = fallback
        self._compiled: Callable[..., Any] | None = None
        self._built = False
        self.error: BaseException | None = None
        self._warned = False

    def __repr__(self) -> str:
        state = (
            "not built"
            if not self._built
            else ("compiled" if self._compiled else "failed")
        )
        return f"CompiledHostKernel({self.__name__!r}, {state})"

    @property
    def module(self) -> ModuleType:
        """The (uncompiled) module that defines the kernel."""
        if isinstance(self._module, str):
            self._module = importlib.import_module(self._module)
        return self._module

    @property
    def python(self) -> Callable[..., Any]:
        """The uncompiled Python function (for signatures and reference results)."""
        return getattr(self.module, self.__name__)

    @property
    def fallback(self) -> Callable[..., Any] | None:
        """What runs when compilation fails, or None for the Python function."""
        return self._fallback

    def build(self) -> Callable[..., Any] | None:
        """Compile now (once); the compiled function, or None if that failed."""
        if not self._built:
            self._built = True
            try:
                self._compiled = getattr(self._compiler(self.module), self.__name__)
            except Exception as error:  # noqa: BLE001 -- no Pyccel or no compiler
                self.error = error
        return self._compiled

    @property
    def compiled(self) -> bool:
        """Whether the compiled version is available (compiles on first access)."""
        return self.build() is not None

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        kernel = self.build()
        if kernel is None:
            if self._fallback is not None:
                kernel = self._fallback
            else:
                if not self._warned:
                    warnings.warn(
                        f"Kernel {self.__name__!r} could not be compiled "
                        f"({self.error!r}); running its uncompiled Python version.",
                        RuntimeWarning,
                        stacklevel=2,
                    )
                    self._warned = True
                kernel = self.python
        return kernel(*args, **kwargs)


def as_kernel_array(value: Any, like: Any, dtype: Any = None) -> Any:
    """`value` as an array the kernel chosen for `like` takes.

    On the device of `like` (a CuPy array if `like` is one, a NumPy array
    otherwise), C-contiguous and with `dtype` (any dtype if None): `value`
    itself when it already is such an array, else one copy, moved to the other
    side if needed (counted by `count_transfers()`). For input arrays of a
    :class:`Kernel` with ``dispatch="arrays"``, whose choice follows the arrays:
    pass the main array (e.g. the grid) as `like`, and the kernel gets
    arguments all on one side::

        convert = functools.partial(xp.kernels.as_kernel_array, like=grid, dtype=float)
        deposit(convert(positions), convert(weights), grid, ...)

    For an array the kernel writes, use :func:`kernel_output`, which copies a
    converted array back.
    """
    if is_gpu(like):
        import cupy

        if not is_gpu(value):
            value = to_cupy(value)
        result = cupy.ascontiguousarray(value, dtype=dtype)
        if _COUNTERS and _is_device_copy(value, result):
            _record(
                "device_copy",
                f"as_kernel_array({_describe(value)})",
                nbytes=_nbytes(result),
            )
        return result
    return np.ascontiguousarray(to_numpy(value), dtype=dtype)


@contextmanager
def kernel_output(out: Any, like: Any, dtype: Any = None) -> Generator[Any]:
    """The buffer a kernel chosen for `like` writes, copied back into `out` after it.

    Yields `out` itself if :func:`as_kernel_array` takes it unchanged (then the
    kernel writes into it directly), else a converted copy whose contents are
    written into `out` when the block ends without an error (moved back to the
    side of `out`)::

        with xp.kernels.kernel_output(result, like=grid, dtype=float) as buffer:
            gather(convert(positions), grid, buffer, ...)
    """
    buffer = as_kernel_array(out, like, dtype)
    yield buffer
    if buffer is not out:
        if is_gpu(out) and not is_gpu(buffer):
            out[...] = to_cupy(buffer)
        elif not is_gpu(out) and is_gpu(buffer):
            out[...] = to_numpy(buffer)
        else:
            out[...] = buffer
