"""Interface for calling Pyccel-compiled kernels with CuPy arrays.

Kernels generated by `pyccel <https://github.com/pyccel/pyccel>`_ are compiled
C/Fortran routines that only understand NumPy (host) arrays. :class:`PyccelKernel`
wraps such a kernel so that it can be called transparently with CuPy (device)
arrays: the arguments are copied to the host before the call, in-place updates
made by the kernel are copied back to the device afterwards, and any arrays
returned by the kernel are moved back to the device.

On the NumPy backend the wrapper is a no-op and the kernel is called directly.
"""

from __future__ import annotations

import copy
from typing import Any, Callable, Sequence

import array_api_compat
import numpy as np

from .xp import _cupy_backend, to_cupy, to_numpy

__all__ = ["PyccelKernel"]


class PyccelKernel:
    """Call a Pyccel-compiled kernel with NumPy or CuPy arrays.

    Parameters
    ----------
    kernel : callable
        The pyccelized kernel (or any callable expecting NumPy arrays).
    use_cupy : bool, optional
        Force host/device conversion on (``True``) or off (``False``). By
        default (``None``) it is decided at call time: conversion happens when
        the active backend is CuPy or when a CuPy array is passed in.
    object_modules : sequence of str, optional
        Module prefixes (e.g. ``("struphy.", "feectools.")``) whose instances
        should be traversed attribute-by-attribute when looking for arrays to
        convert. Objects from other modules are passed through untouched.

    Examples
    --------
    >>> from cunumpy.kernel import PyccelKernel
    >>> kernel = PyccelKernel(my_pyccelized_function)
    >>> kernel(out, x, y)  # `out`, `x`, `y` may be NumPy or CuPy arrays
    """

    def __init__(
        self,
        kernel: Callable[..., Any],
        use_cupy: bool | None = None,
        object_modules: Sequence[str] = (),
    ) -> None:
        self._kernel = kernel
        self._use_cupy = use_cupy
        self._object_modules = tuple(object_modules)

    def __repr__(self) -> str:
        return f"PyccelKernel(kernel={self.name!r}, use_cupy={self.use_cupy!r})"

    def _convert_to_numpy(
        self,
        value: Any,
        converted: list[tuple[Any, np.ndarray]],
        memo: dict[int, Any],
    ) -> Any:
        """Recursively replace CuPy arrays in `value` by host copies.

        Every replacement is appended to `converted` as a
        ``(device_array, host_copy)`` pair.

        `memo` maps ``id(original) -> converted`` and is shared across all
        arguments of a single call. It serves two purposes: a device array
        reachable by several paths is copied to the host exactly once (so the
        kernel sees one shared array, as the caller intended, and the write-back
        happens once), and reference cycles terminate instead of recursing
        forever. Everything traversed here stays reachable from the caller's
        arguments for the duration of the call, so the `id` keys cannot be
        reused by unrelated objects.
        """
        key = id(value)
        if key in memo:
            return memo[key]

        if array_api_compat.is_cupy_array(value):
            value_np = to_numpy(value)
            memo[key] = value_np
            converted.append((value, value_np))
            return value_np

        if isinstance(value, tuple):
            # A tuple cannot be memoized before its items are converted, but it
            # can only take part in a cycle through a mutable container, and
            # those are memoized before they are filled in below.
            value_np = tuple(
                self._convert_to_numpy(item, converted, memo) for item in value
            )
            memo[key] = value_np
            return value_np

        if isinstance(value, list):
            value_np = []
            memo[key] = value_np
            value_np.extend(
                self._convert_to_numpy(item, converted, memo) for item in value
            )
            return value_np

        if isinstance(value, dict):
            value_np = {}
            memo[key] = value_np
            for k, v in value.items():
                value_np[k] = self._convert_to_numpy(v, converted, memo)
            return value_np

        if hasattr(value, "__dict__") and value.__class__.__module__.startswith(
            self._object_modules
        ):
            # Shallow-copy the object so the caller's instance keeps pointing at
            # its device arrays; only the copy holds the host views.
            value_np = copy.copy(value)
            memo[key] = value_np
            for name, attr in vars(value).items():
                setattr(value_np, name, self._convert_to_numpy(attr, converted, memo))
            return value_np

        return value

    @staticmethod
    def _convert_from_numpy(value: Any) -> Any:
        """Move NumPy arrays returned by the kernel back to the device."""
        if isinstance(value, np.ndarray):
            return to_cupy(value)
        if isinstance(value, tuple):
            return tuple(PyccelKernel._convert_from_numpy(item) for item in value)
        if isinstance(value, list):
            return [PyccelKernel._convert_from_numpy(item) for item in value]
        return value

    def _contains_cupy(self, value: Any, seen: set[int] | None = None) -> bool:
        """Whether `value` holds a CuPy array, following the same traversal
        rules as :meth:`_convert_to_numpy`.

        `seen` tracks already-visited containers so that reference cycles
        terminate.
        """
        if array_api_compat.is_cupy_array(value):
            return True

        if seen is None:
            seen = set()
        if id(value) in seen:
            return False

        if isinstance(value, (tuple, list)):
            seen.add(id(value))
            return any(self._contains_cupy(item, seen) for item in value)

        if isinstance(value, dict):
            seen.add(id(value))
            return any(self._contains_cupy(item, seen) for item in value.values())

        if hasattr(value, "__dict__") and value.__class__.__module__.startswith(
            self._object_modules
        ):
            seen.add(id(value))
            return any(self._contains_cupy(attr, seen) for attr in vars(value).values())

        return False

    def _needs_conversion(self, args: tuple[Any, ...], kwargs: dict[str, Any]) -> bool:
        if self._use_cupy is not None:
            return self._use_cupy
        if _cupy_backend():
            return True
        # The backend is NumPy, but individual CuPy arrays may still have been
        # passed in explicitly.
        return any(self._contains_cupy(value) for value in (*args, *kwargs.values()))

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        if not self._needs_conversion(args, kwargs):
            return self._kernel(*args, **kwargs)

        # Convert CuPy arrays in args/kwargs to NumPy arrays on the host. The
        # memo is shared across args and kwargs so that an array passed more
        # than once stays a single array on the host too.
        converted: list[tuple[Any, np.ndarray]] = []
        memo: dict[int, Any] = {}
        args_np = [self._convert_to_numpy(x, converted, memo) for x in args]
        kwargs_np = {
            k: self._convert_to_numpy(v, converted, memo) for k, v in kwargs.items()
        }

        result = self._kernel(*args_np, **kwargs_np)

        # Copy in-place kernel updates back to the device arrays.
        for device_array, host_array in converted:
            device_array[...] = to_cupy(host_array)

        return self._convert_from_numpy(result)

    @property
    def name(self) -> str:
        """Name of the wrapped kernel."""
        return getattr(self._kernel, "__name__", type(self._kernel).__name__)

    @property
    def kernel(self) -> Callable[..., Any]:
        """The wrapped kernel."""
        return self._kernel

    @property
    def use_cupy(self) -> bool:
        """Whether calls currently convert between device and host arrays."""
        if self._use_cupy is not None:
            return self._use_cupy
        return _cupy_backend()

    @property
    def object_modules(self) -> tuple[str, ...]:
        """Module prefixes whose instances are traversed for arrays."""
        return self._object_modules
